/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TestTokenRecipientInterface extends ethers.utils.Interface {
  functions: {
    "balances(address,address)": FunctionFragment;
    "claim(address)": FunctionFragment;
    "handleWithTokens(uint32,bytes32,bytes,address,uint256)": FunctionFragment;
    "lastAmount()": FunctionFragment;
    "lastData()": FunctionFragment;
    "lastSender()": FunctionFragment;
    "lastToken()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "balances",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [string]): string;
  encodeFunctionData(
    functionFragment: "handleWithTokens",
    values: [BigNumberish, BytesLike, BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastData", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastSender",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleWithTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastAmount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastSender", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastToken", data: BytesLike): Result;

  events: {
    "ReceivedCall(address,uint256,string)": EventFragment;
    "ReceivedMessage(uint32,bytes32,string,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ReceivedCall"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceivedMessage"): EventFragment;
}

export type ReceivedCallEvent = TypedEvent<
  [string, BigNumber, string] & {
    caller: string;
    amount: BigNumber;
    message: string;
  }
>;

export type ReceivedMessageEvent = TypedEvent<
  [number, string, string, string, BigNumber] & {
    origin: number;
    sender: string;
    message: string;
    token: string;
    amount: BigNumber;
  }
>;

export class TestTokenRecipient extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestTokenRecipientInterface;

  functions: {
    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claim(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    handleWithTokens(
      _origin: BigNumberish,
      _sender: BytesLike,
      _data: BytesLike,
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lastAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastData(overrides?: CallOverrides): Promise<[string]>;

    lastSender(overrides?: CallOverrides): Promise<[string]>;

    lastToken(overrides?: CallOverrides): Promise<[string]>;
  };

  balances(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claim(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  handleWithTokens(
    _origin: BigNumberish,
    _sender: BytesLike,
    _data: BytesLike,
    _token: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lastAmount(overrides?: CallOverrides): Promise<BigNumber>;

  lastData(overrides?: CallOverrides): Promise<string>;

  lastSender(overrides?: CallOverrides): Promise<string>;

  lastToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(token: string, overrides?: CallOverrides): Promise<void>;

    handleWithTokens(
      _origin: BigNumberish,
      _sender: BytesLike,
      _data: BytesLike,
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    lastAmount(overrides?: CallOverrides): Promise<BigNumber>;

    lastData(overrides?: CallOverrides): Promise<string>;

    lastSender(overrides?: CallOverrides): Promise<string>;

    lastToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ReceivedCall(address,uint256,string)"(
      caller?: string | null,
      amount?: null,
      message?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { caller: string; amount: BigNumber; message: string }
    >;

    ReceivedCall(
      caller?: string | null,
      amount?: null,
      message?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { caller: string; amount: BigNumber; message: string }
    >;

    "ReceivedMessage(uint32,bytes32,string,address,uint256)"(
      origin?: BigNumberish | null,
      sender?: BytesLike | null,
      message?: null,
      token?: null,
      amount?: null
    ): TypedEventFilter<
      [number, string, string, string, BigNumber],
      {
        origin: number;
        sender: string;
        message: string;
        token: string;
        amount: BigNumber;
      }
    >;

    ReceivedMessage(
      origin?: BigNumberish | null,
      sender?: BytesLike | null,
      message?: null,
      token?: null,
      amount?: null
    ): TypedEventFilter<
      [number, string, string, string, BigNumber],
      {
        origin: number;
        sender: string;
        message: string;
        token: string;
        amount: BigNumber;
      }
    >;
  };

  estimateGas: {
    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    handleWithTokens(
      _origin: BigNumberish,
      _sender: BytesLike,
      _data: BytesLike,
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lastAmount(overrides?: CallOverrides): Promise<BigNumber>;

    lastData(overrides?: CallOverrides): Promise<BigNumber>;

    lastSender(overrides?: CallOverrides): Promise<BigNumber>;

    lastToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    handleWithTokens(
      _origin: BigNumberish,
      _sender: BytesLike,
      _data: BytesLike,
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lastAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
