/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IInterchainGasPaymaster,
  IInterchainGasPaymasterInterface,
} from "../IInterchainGasPaymaster";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_messageId",
        type: "bytes32",
      },
      {
        internalType: "uint32",
        name: "_destinationDomain",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_gasAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_refundAddress",
        type: "address",
      },
    ],
    name: "payForGas",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_destinationDomain",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_gasAmount",
        type: "uint256",
      },
    ],
    name: "quoteGasPayment",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IInterchainGasPaymaster__factory {
  static readonly abi = _abi;
  static createInterface(): IInterchainGasPaymasterInterface {
    return new utils.Interface(_abi) as IInterchainGasPaymasterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInterchainGasPaymaster {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IInterchainGasPaymaster;
  }
}
