/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILiquidityLayerRouter,
  ILiquidityLayerRouterInterface,
} from "../ILiquidityLayerRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_destinationDomain",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "_recipientAddress",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_bridge",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "_messageBody",
        type: "bytes",
      },
    ],
    name: "dispatchWithTokens",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILiquidityLayerRouter__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidityLayerRouterInterface {
    return new utils.Interface(_abi) as ILiquidityLayerRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILiquidityLayerRouter {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILiquidityLayerRouter;
  }
}
