/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILiquidityLayerMessageRecipient,
  ILiquidityLayerMessageRecipientInterface,
} from "../ILiquidityLayerMessageRecipient";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "origin",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "sender",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "handleWithTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILiquidityLayerMessageRecipient__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidityLayerMessageRecipientInterface {
    return new utils.Interface(
      _abi
    ) as ILiquidityLayerMessageRecipientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILiquidityLayerMessageRecipient {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILiquidityLayerMessageRecipient;
  }
}
